import { FilterComponent } from './../../filter/filter.component';
import { MatDialog, MatDialogConfig } from '@angular/material/dialog';
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

const ELEMENT_DATA = [
  {
    patientName: 'Ajith Sharma',
    bloodType: 'A+',
    componentType: 'Plasma',
    patientAge: 35,
    Gender: 'Male',
    Location: 'Bangalore',
    dateOfRequest: '23-02-2022',
    dateOfRequirement: '23-02-2022',
    remarkByDoctor: 'N/A',
    uploadedDocuments: 'File.pdf',
    issueBlood: 'Issued',
  },
  {
    patientName: 'Ajith Sharma',
    bloodType: 'A+',
    componentType: 'Plasma',
    patientAge: 35,
    Gender: 'Male',
    Location: 'Bangalore',
    dateOfRequest: '23-02-2022',
    dateOfRequirement: '23-02-2022',
    remarkByDoctor: 'N/A',
    uploadedDocuments: 'File.pdf',
    issueBlood: 'Issued',
  },
  {
    patientName: 'Ajith Sharma',
    bloodType: 'A+',
    componentType: 'Plasma',
    patientAge: 35,
    Gender: 'Male',
    Location: 'Bangalore',
    dateOfRequest: '23-02-2022',
    dateOfRequirement: '23-02-2022',
    remarkByDoctor: 'N/A',
    uploadedDocuments: 'File.pdf',
    issueBlood: 'Issued',
  },
  {
    patientName: 'Ajith Sharma',
    bloodType: 'A+',
    componentType: 'Plasma',
    patientAge: 35,
    Gender: 'Male',
    Location: 'Bangalore',
    dateOfRequest: '23-02-2022',
    dateOfRequirement: '23-02-2022',
    remarkByDoctor: 'N/A',
    uploadedDocuments: 'File.pdf',
    issueBlood: 'Issued',
  },
  {
    patientName: 'Ajith Sharma',
    bloodType: 'A+',
    componentType: 'Plasma',
    patientAge: 35,
    Gender: 'Male',
    Location: 'Bangalore',
    dateOfRequest: '23-02-2022',
    dateOfRequirement: '23-02-2022',
    remarkByDoctor: 'N/A',
    uploadedDocuments: 'File.pdf',
    issueBlood: 'Issued',
  },
  {
    patientName: 'Ajith Sharma',
    bloodType: 'A+',
    componentType: 'Plasma',
    patientAge: 35,
    Gender: 'Male',
    Location: 'Bangalore',
    dateOfRequest: '23-02-2022',
    dateOfRequirement: '23-02-2022',
    remarkByDoctor: 'N/A',
    uploadedDocuments: 'File.pdf',
    issueBlood: 'Issued',
  },
  {
    patientName: 'Ajith Sharma',
    bloodType: 'A+',
    componentType: 'Plasma',
    patientAge: 35,
    Gender: 'Male',
    Location: 'Bangalore',
    dateOfRequest: '23-02-2022',
    dateOfRequirement: '23-02-2022',
    remarkByDoctor: 'N/A',
    uploadedDocuments: 'File.pdf',
    issueBlood: 'Issued',
  },
  {
    patientName: 'Ajith Sharma',
    bloodType: 'A+',
    componentType: 'Plasma',
    patientAge: 35,
    Gender: 'Male',
    Location: 'Bangalore',
    dateOfRequest: '23-02-2022',
    dateOfRequirement: '23-02-2022',
    remarkByDoctor: 'N/A',
    uploadedDocuments: 'File.pdf',
    issueBlood: 'Issued',
  },
  {
    patientName: 'Ajith Sharma',
    bloodType: 'A+',
    componentType: 'Plasma',
    patientAge: 35,
    Gender: 'Male',
    Location: 'Bangalore',
    dateOfRequest: '23-02-2022',
    dateOfRequirement: '23-02-2022',
    remarkByDoctor: 'N/A',
    uploadedDocuments: 'File.pdf',
    issueBlood: 'Issued',
  },
  {
    patientName: 'Ajith Sharma',
    bloodType: 'A+',
    componentType: 'Plasma',
    patientAge: 35,
    Gender: 'Male',
    Location: 'Bangalore',
    dateOfRequest: '23-02-2022',
    dateOfRequirement: '23-02-2022',
    remarkByDoctor: 'N/A',
    uploadedDocuments: 'File.pdf',
    issueBlood: 'Issued',
  },
  {
    patientName: 'Ajith Sharma',
    bloodType: 'A+',
    componentType: 'Plasma',
    patientAge: 35,
    Gender: 'Male',
    Location: 'Bangalore',
    dateOfRequest: '23-02-2022',
    dateOfRequirement: '23-02-2022',
    remarkByDoctor: 'N/A',
    uploadedDocuments: 'File.pdf',
    issueBlood: 'Issued',
  },
  {
    patientName: 'Ajith Sharma',
    bloodType: 'A+',
    componentType: 'Plasma',
    patientAge: 35,
    Gender: 'Male',
    Location: 'Bangalore',
    dateOfRequest: '23-02-2022',
    dateOfRequirement: '23-02-2022',
    remarkByDoctor: 'N/A',
    uploadedDocuments: 'File.pdf',
    issueBlood: 'Issued',
  },
  {
    patientName: 'Ajith Sharma',
    bloodType: 'A+',
    componentType: 'Plasma',
    patientAge: 35,
    Gender: 'Male',
    Location: 'Bangalore',
    dateOfRequest: '23-02-2022',
    dateOfRequirement: '23-02-2022',
    remarkByDoctor: 'N/A',
    uploadedDocuments: 'File.pdf',
    issueBlood: 'Issued',
  },
  {
    patientName: 'Ajith Sharma',
    bloodType: 'A+',
    componentType: 'Plasma',
    patientAge: 35,
    Gender: 'Male',
    Location: 'Bangalore',
    dateOfRequest: '23-02-2022',
    dateOfRequirement: '23-02-2022',
    remarkByDoctor: 'N/A',
    uploadedDocuments: 'File.pdf',
    issueBlood: 'Issued',
  },
  {
    patientName: 'Ajith Sharma',
    bloodType: 'A+',
    componentType: 'Plasma',
    patientAge: 35,
    Gender: 'Male',
    Location: 'Bangalore',
    dateOfRequest: '23-02-2022',
    dateOfRequirement: '23-02-2022',
    remarkByDoctor: 'N/A',
    uploadedDocuments: 'File.pdf',
    issueBlood: 'Issued',
  },
  {
    patientName: 'Ajith Sharma',
    bloodType: 'A+',
    componentType: 'Plasma',
    patientAge: 35,
    Gender: 'Male',
    Location: 'Bangalore',
    dateOfRequest: '23-02-2022',
    dateOfRequirement: '23-02-2022',
    remarkByDoctor: 'N/A',
    uploadedDocuments: 'File.pdf',
    issueBlood: 'Issued',
  },
  {
    patientName: 'Ajith Sharma',
    bloodType: 'A+',
    componentType: 'Plasma',
    patientAge: 35,
    Gender: 'Male',
    Location: 'Bangalore',
    dateOfRequest: '23-02-2022',
    dateOfRequirement: '23-02-2022',
    remarkByDoctor: 'N/A',
    uploadedDocuments: 'File.pdf',
    issueBlood: 'Issued',
  },
];
@Component({
  selector: 'app-allBloodReq',
  templateUrl: './allBloodReq.component.html',
  styleUrls: ['./allBloodReq.component.css'],
})
export class AllBloodReqComponent implements OnInit {
  dataSource = ELEMENT_DATA;
  displayedColumns: string[] = [
    'Patient Name',
    'Blood type',
    'Component type',
    'Patient age',
    'Gender',
    'Location',
    'Date of request',
    'Date of requirement',
    'Remark by doctor',
    'Uploaded documents',
    'Issue blood',
  ];

  constructor(private dialog: MatDialog, private router: Router) {}

  ngOnInit() {}

  onFilter(event) {
    const dialogConfig = new MatDialogConfig();
    let targetAttr = event.target.getBoundingClientRect();

    dialogConfig.height = 'auto';
    dialogConfig.width = '350px';
    dialogConfig.panelClass = 'custom-dialog-container';
    dialogConfig.position = {
      top: targetAttr.y + targetAttr.height - 7 + 'px',
      left: targetAttr.x + targetAttr.width - 5 + 'px',
    };
    this.dialog.open(FilterComponent, dialogConfig);
  }

  onBlgReqView() {
    this.router.navigate(['/dashboard/bloodRequests']);
  }
}
